# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'kavak' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for kavak
  pod 'ObjectMapper', '~> 3.4'
  pod 'SDWebImage'

  target 'kavakTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'kavakUITests' do
    # Pods for testing
  end

end
